[package]
name = "epics-ca-sys"
version = "0.1.0"
edition = "2021"
links = "ca"

description = "Raw bindings for EPICS Channel Access library"
keywords = ["epics"]
categories = ["science", "api-bindings"]

[dependencies]
libc = "0.2"
